### ISSUE TITLE
Make a F-Droid compatible version

### ISSUE THREAD

**Issue by BenSartor** [simlar/simlar-android#151]
### Motivivation

Many privacy aware users want to install only open source software on their smartphones.
### Problem

Currently Simlar depends on the Google Play Services Lib (propitary) in order to receive Push-Notifications. This dependency is checked at run time and Simlar (at moment) won't stop complaining if it is missing.
### Analysis

In order to drop the dependency on Google Play, we have to drop Googles Push Notifcations. Sadly, there is no open source alternative to it. At least I don't know one.
Simlar uses Push-Notifications in order to signal incoming calls. We have to find a different way for this. There are two obvious solutions, that both do not completely satisfy me:
### Solution 1: SMS

Send SMS instead of Push Notifications.
Drawbacks:
- Meta data is back to the telecomunication providers
- User has to pay for an sms each time he wants to call someone.
### Solution 2: Permanent connection

Simlar holds a permanent connection to the Simlar server. Of course this requires Simlar to constantly run in the background. An App constantly running in the background obviously consumes more power than one not running at all. So people tend to quit Simlar. Which means these people can almost never recieve calls and the ones trying to call them get the impressions Simlar is not working.

Personaly I tend to Solution 2. What Do think?
## Update 2015-03-13

Meanwhile I have spent some time implementing solution 2.
If you are fealing brave, you might be intrested in installing a test version. A direct download may be found here:
https://www.simlar.org/devel/android/Simlar-alwaysOnline.apk

A preliminary fdroid repository maybe found here:
https://www.simlar.org/fdroid/repo

As long as the source is not yet reviewed, it will stay in the devel branch where even commits may change. Keep in mind these are test version and may change, break or may be removed at any time. However giving feedback on these versions helps a lot to get an offical release ready.

**Comment by countrygeek** [comment]
This is definitely needed, I don't have any GAPPS on my CM Phone.

For a replacement of GCM there were some ideas mentioned here:
https://github.com/WhisperSystems/TextSecure/issues/127#issuecomment-36145890
And even if method 1, you could use textsecure in combination to hide meta.

If method 2, I'd feel more comfortable if the server was opensource too and I could run my own node.

**Comment by h-2** [comment]
Apperently there still is a working open source GCM client:
http://androidosp.blogspot.de/2014/07/using-google-cloud-messaging-with-aosp.html

And what about other Push solutions like this:
https://developer.motorolasolutions.com/docs/DOC-2315

**Comment by BenSartor** [comment]
As far as I understand MQTT, after only having a short look, it adds a service to your holding a constant connection to your server. Basically solution 2.

Using the deprecated open source version of GCM sounds interesting. Do you have more information?

**Comment by h-2** [comment]
> As far as I understand MQTT, after only having a short look, it adds a service to your holding a constant connection to your server. Basically solution 2.

Concerning solution 2 in general: maybe one could add a button for people without push that indicates that you might expect to receive a call and that triggers the always-on behaviour and/or configure the always-on to just be automatically on on certain wifis. Thats not a perfect solution since it won't enable ubiquitous encryption, but maybe it will be better than draining the battery.

Concerning solution 1: I actually think this is the better solution, though. If two simlars communicate they can tell each other whether one or both do by without push, then if one can't reach the other, it will send a "go online" message (that should of course be handled automatically in some way). This should f course be communicated clearly to the user, or she could be asked ("Your contact doesn't have push and is not responding, send her a wake-up text message over your regular carrier plan?" Yes? No? Always? )
Many people nowadays have unlimited free texts, so it would be a minor data leakage, but still a giant improvement over the current (unencrypted) call.

> Using the deprecated open source version of GCM sounds interesting. Do you have more information?

I discussed this over at Kontalk and the reasoning there was that there are still parts of the client that are proprietary:
https://github.com/kontalk/androidclient/issues/277
I don't know enough about Android to say for sure...

**Comment by h-2** [comment]
Maybe even a better solution similar to 1:
 * have all regular calls incoming to the phone intercepted by simlar
 * have a simlar server *call* the phone to wake it up
 * always silently dismiss calls from this number 
 * this won't generate costs, since the call isn't picked up
 * if it actually is picked up, play a message "This is the simlar server, if you are hearing this message your client is misconfigured. Please update it or unregister at FOO.COM/BAR if you do not wish to use simlar anymore."

**Comment by BenSartor** [comment]
According to the kontalk discussion the deprecated open source version of GCM still needs Google Play Services to be installed on the phone. So, this is no option.

Letting the server do a noraml phone call to wake up the client sounds interesting. Maybe it is worth to have a deeper look at it. But it definitly is a lot of work for very few uesers. Does anybody know an app implementing this?

@h-2 Did you try the test version implementing solution 2?

**Comment by DennisKlipp** [comment]
Hi Guys,

about the idea to trigger the app with a gsm call, I see a few difficult solvable security issues.

The only way to block the incoming call on recipient side is simlar. But we have no chance to check, if the app is running or still installed. In case we hang up the call directly, when the call established it will generates cost, too.
The second issue I see: This functionality could make fraud possible. 

Regards,
Dennis

**Comment by h-2** [comment]
> Letting the server do a noraml phone call to wake up the client sounds interesting. Maybe it is worth to have a deeper look at it.

I was just brainstorming, but the more I think about it, it might actually be a cool method.

> But it definitly is a lot of work for very few uesers. 

A tiny percentage of the entire android users, true, but not a tiny percentage of security conscious users. Also having a workaround for security nerds and being able to claim that it works with 100% free and open source phones does increase the overall trust in the project and its developers ;)

> The only way to block the incoming call on recipient side is simlar. But we have no chance to check, if the app is running or still installed. 

Indeed, thats why I proposed the small text being read and automatically disabling a person if she picks up the call e.g. two times.

> In case we hang up the call directly, when the call established it will generates cost, too.

I heard this was the case in the US. In Europe phone calls that aren't picked up never generate costs, even international calls. Also incoming calls never generate costs.  In the case where a person has deinstalled simlar and answers the call, yes this will generate costs. However both Telegram and Kontalk have phone call verification for when sms verification (for the number) fails, so the costs don't seem to be too high. I think this could be handled by donations...

> The second issue I see: This functionality could make fraud possible. 

How is that?

Thanks for considering it anyway!

PS: Will try the apk from above asap, although I did already have the experience that an always-on-textsecure mor than halves my battery-time.

**Comment by h-2** [comment]
> @h-2 Did you try the test version implementing solution 2?

@BenSartor I have the version running now and also verified with another f-droid based install that it works! It is not ideal for battery life, but since I have k-9 mail, Kontalk, Telegram that all poll their servers at different intervals it doesn't make much of a difference anymore I think...

I have notices though, that with Simlar active my screen never goes off automatically, though. Looks like a bug...

In any case, thanks for working on the F-Droid version!

**Comment by SudoAccess** [comment]
i just saw the motorolasolutions push server. i kind of like it. i will take a few days off and implement something with it. i think its a good way to go forward with. :)

**Comment by h-2** [comment]
Great to hear!

**Comment by BenSartor** [comment]
@SudoAccess Cool!

@h2 Nice to hear from you. This sounds like a bug . I have just created an issue: #218

**Comment by BenSartor** [comment]
@h-2 I think the bug you have reported is fixed in the f-droid version now. Would you be so kind and report if the problem went away at yout phone, too?
