### ISSUE TITLE
How could i use own server with simlar-android?

### ISSUE THREAD

**Issue by awesomek** [simlar/simlar-android#201]
This is really good project!!
I want to use make my own server with Simlar.
May i have your idea?? 

Thanks.

**Comment by BenSartor** [comment]
This is s.th. we have been thinking about since the begining of simlar but haven't found a realy cool solution, yet. Let me try to explain:

### The island server
In this scenario the servers do not talk to each other. That means, users connected to one server can not contact users connected on the other servers. It should be relatively easy to implement and we already have a second server running for testing.

### The interconnected server
This is the cool solution which should work a bit like email. Meaning that a client connected to one server may contact any other client connected to any other server and no central server gets any kind of metadata. I'm thinking of s.th. like a PIR-based ENUM, but have not come far. Any idea of privacy preserving protocol is more than welcome.

### Prerequisites for running a Simlar server
At the moment the Simlar server needs to be able to send SMS and Push-Notifications. So you need to have an account as a goolge developer and as an apple developer. Furthermore you would need a SMS-Gateway.

### Changes in the Simlar client
You need to compile your own Simlar-Client. Atleast you will have to change the server adress, the push settings and the certificate for communicating with the server. Furthermore I would suggest to change the product id in order to have both Simlar and your new App installed on the phone.

Please let me know what you think. Is an island-server solution interesting for you even if you have to pay apple, google and your sms-provider?

**Comment by jritzerfeld** [comment]
No response.
