### ISSUE TITLE
Without SMS verification Closed group Test with our own sip server

### ISSUE THREAD

**Issue by MyraBaba** [simlar/simlar-android#257]
Dear Sir,

We would like to use and test your android solution in our closed group (35 people) with out sms verification and in our own sip server instead of yours.  We will manually enter the user to server.

Is this possible ? May we use this way ?

If yes what will be the steps and your advise to start configuration ?

Thanks..

**Comment by MyraBaba** [comment]
I would like to get little more infor about the server side if possible.  What is the sip server specification and suggested one ?  If other side of the FORCE more visible we can improve our practice faster :)

**Comment by BenSartor** [comment]
Hello @MyraBaba,

we use kamailio as sip server. But running your own server is not supported at the moment. We are working on a rewrite of our scripts in java in order to open source them. Documentation will fallow, but do not expect it to happen any time soon as my spare time is very limited at the moment.

**Comment by MyraBaba** [comment]
Hi Ben,

How is the progress of the rewriting scripts in order to use our kamailio sip server ?

Any news ?
