### ISSUE TITLE
Does this app "track and report"?

### ISSUE THREAD

**Issue by ShockedCoder** [simlar/simlar-android#703]
![Sus](https://i.ibb.co/9c7Xx3x/Screenshot-20221129-153523.jpg)

I haven't found an explanation in the issues or in the readme, since most that have warning usually have in their readme why it's so.

**Comment by BenSartor** [comment]
Hi @ShockedCoder,

as far as I understood it, we got these two flags in froid, because of the following reasons.

> Promotes non-libre network services

We published the source of the s [simlar-server](https://github.com/simlar/simlar-server). However the app does not support choosing another server.

> Tracks or reports your activity

When you call s.o. with Simlar the simlar-server handles the signaling. That means it knows that your number is calling another number. However we do not store this data permanently.

We try hard to only store the minimum required data.

**Comment by BenSartor** [comment]
We want to keep it simple.

**Comment by ShockedCoder** [comment]
Fair 'nough, I guess?

**Comment by theAkito** [comment]
> We want to keep it simple.

I just want to point out that this explanation is bullshit.

You can keep the app just as simple & allow custom servers. Such a functionality is very normal & expected in all kinds of open source software involving communication, especially when it is centered around security.

What's the real reason for not providing the option to change servers?
Gathering phone numbers?

**Comment by ShockedCoder** [comment]
> I just want to point out that this explanation is bullshit.

Yeah, I agree with you. That's why I've just decided to just not to use the app.
